### PR TITLE
Release note

### PR DESCRIPTION
**Pull request by zaaraameera2014**
Ok

### CODE REVIEW

**Comment by zaaraameera2014** [comment]
Fhuippplll

**Comment by zaaraameera2014** [comment]
Ok

**Comment by Wphelp98737** [comment]
X
blue-large

**Comment by willnorris** [comment]
To report bugs or submit patches to Android, please follow the instructions at http://source.android.com/source/contributing.html.  More information on these mirrors (like the fact that issues and pull requests are ignored) is available at http://android.github.io/.

**Pull request closed without merging**
